wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: ".iot.home.arpa"
  ap:
    ssid: "${friendly_name} AP"
    password: "kukuryku"

improv_serial:

captive_portal:

esp32_improv:
  authorizer: none

logger:

api:
  password: ""

ota:
  platform: esphome
  password: ""

web_server:
  port: 8080

i2c:
  sda: GPIO23
  scl: GPIO22
  scan: false


esphome:
  name: laz-led-mcu
  friendly_name: Sterownik LED Lazienka
  name_add_mac_suffix: false
  project:
    name: iot.home
    version: '1.0'


esp32:
  board: esp32dev
  framework:
    type: arduino
    version: recommended

  #area:

globals:
  - id: current_values
    type: float
    restore_value: no
    initial_value: '0.2'


output:
  - platform: ledc
    pin: GPIO0
    id: output_led
    zero_means_zero: true
    frequency: 2441Hz
    
button:
  - platform: template
    id: btn_minus
    name: "Przycisk Minus"
    on_press:
      then:
        - light.dim_relative:
            id: light_0
            relative_brightness: -5%
        - lambda: |-
            id(current_values) = id(light_0).current_values.get_brightness();

  - platform: template
    name: "Przycisk Plus"
    id: button_up
    on_press:
      then:
        - light.dim_relative:
            id: light_0
            relative_brightness: 5%
        - lambda: |-
            id(current_values) = id(light_0).current_values.get_brightness();

light:
  - platform: monochromatic
    output: output_led
    name: "Lazienka LED"
    id: light_0
    restore_mode: RESTORE_DEFAULT_OFF            