packages:
  diag: !include common/diag.yaml
  api: !include common/api.yaml
  wifi: !include common/wifi.yaml
  logger: !include common/logger.yaml
  webserver: !include common/webserver.yaml
  board: !include common/board-arduino.yaml
  ota: !include common/ota.yaml

esphome:  
  name: lazienka-led
  comment: "Sterowanie oświetleniem LED"
  friendly_name: "Oświetlenie lustra"
  area: bathroom  
  name_add_mac_suffix: false
  project:
    name: lazienka-led.iot
    version: '1.0'
    
globals:
  - id: current_values
    type: float
    restore_value: yes
    initial_value: '0.1'
    
wifi:
  manual_ip:
      static_ip: 10.1.30.4
      gateway: 10.1.30.1
      subnet: 255.255.255.0
      
button:
  - platform: restart
    name: "Restart"    

  - platform: template
    id: btn_minus
    name: "Minus"
    on_press:
      then:
        - light.dim_relative:
            id: light_0
            relative_brightness: -2%
        - lambda: |-
            id(current_values) = id(light_0).current_values.get_brightness();

  - platform: template
    name: "Plus"    
    id: button_up
    on_press:
      then:
        - light.dim_relative:
            id: light_0
            relative_brightness: 2%
        - lambda: |-
            id(current_values) = id(light_0).current_values.get_brightness();

output:
  - platform: ledc
    pin: GPIO0
    id: output_led
    frequency: 1200Hz
    zero_means_zero: true
    min_power: 0.01
    max_power: 1
    
  - platform: gpio
    pin: GPIO13
    id: wyjscie_g13


light:
  - platform: monochromatic
    id: light_0
    name: "Łazienka LED"
    output: output_led
    restore_mode: RESTORE_DEFAULT_OFF
    effects:
      - pulse:
          name: "Fast Pulse"
          transition_length: 0.4s
          update_interval: 1.5s
          min_brightness: "30%"
          max_brightness: "100%"
      - random:
          name: "Random Effect"
          transition_length: 3s
          update_interval: 5s
      - pulse:
          name: "Slow Pulse"
          transition_length: 500ms
          update_interval: 2s
      - pulse:
          name: "Asymmetrical Pulse"
          transition_length:
            on_length: 1s
            off_length: 500ms
          update_interval: 1.5s

web_server:
  sorting_groups:
    - id: heating_group
      name: "Ogrzewanie"
      sorting_weight: 4
      
    - id: advanced_group
      name: "Zaawansowane"
      sorting_weight: 10

    - id: device_info_group
      name: "Info"
      sorting_weight: 11

    - id: bme280_sensor
      name: "BME280"
      sorting_weight: 8