esphome:
  name: ogrzewanie-mcu
  friendly_name: Sterownik Ogrzewania
  name_add_mac_suffix: false
  project:
    name: iot.home
    version: '1.0'

esp32:
  board: esp32dev
  framework:
    type: arduino
    version: recommended

mdns:
  disabled: false

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: ".iot.home.arpa"
  
  ap:
    ssid: "Ogrzewanie MCU AP"
    password: "kukuryku"

captive_portal:

esp32_improv:
  authorizer: none

modbus:

one_wire:
  - platform: gpio
    pin: GPIO14
    id: one_wire_1      

logger:
  baud_rate: 0

api:
  password: ""

ota:
  platform: esphome
  password: ""

web_server:
  port: 8080
  version: 3
  include_internal: true

uart:
  rx_pin: 3
  tx_pin: 1
  baud_rate: 9600

i2c:
  sda: GPIO23
  scl: GPIO22
  scan: false

binary_sensor:
  - platform: template
    name: "Grzałka - Stan"
    lambda: |-
      return (id(grzalka_moc).state > 5.0);
    id: grzalka_status



button:
  - platform: template
    name: "Test 1-wire bus"
    internal: true
    on_press: 
      then:
        - lambda: |-
            id(one_wire_1).search();
            id(one_wire_1).dump_config();
sensor:
  - platform: uptime
    name: "Uptime"
    id: mcu_uptime

  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    name: "WiFi Signal dB"
    id: wifi_signal_db
    update_interval: 30s
    entity_category: "diagnostic"

  - platform: copy # Reports the WiFi signal strength in %
    source_id: wifi_signal_db
    name: "WiFi Signal Percent"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "Signal %"
    entity_category: "diagnostic"
    device_class: ""

  - platform: dallas_temp
    id: temp_1
    address: "0xcc65c7d446950328"
    one_wire_id: one_wire_1
    name: "Temp Pod. Salon #1"
    unit_of_measurement: "°C"
    icon: "mdi:water-percent"
    device_class: "temperature"
    state_class: "measurement"
    accuracy_decimals: 1    

  - platform: dallas_temp  
    id: temp_2
    one_wire_id: one_wire_1
    address: "0x9751cfd446dd8928"
    name: "Temp Pod. Salon #2"
    unit_of_measurement: "°C"
    icon: "mdi:water-percent"
    device_class: "temperature"
    state_class: "measurement"
    accuracy_decimals: 1    
    
  - platform: dallas_temp
    id: temp_3  
    address: "0x943c01e076247d28"
    name: "Temp Pod. Salon #3"
    one_wire_id: one_wire_1
    unit_of_measurement: "°C"
    icon: "mdi:water-percent"
    device_class: "temperature"
    state_class: "measurement"
    accuracy_decimals: 1
    
  - platform: dallas_temp
    id: temp_4
    address: "0x9e3c01e076378028"
    one_wire_id: one_wire_1
    name: "Temp Pod. Pokój"
    unit_of_measurement: "°C"
    icon: "mdi:water-percent"
    device_class: "temperature"
    state_class: "measurement"
    accuracy_decimals: 1    

  - platform: dallas_temp
    id: temp_5
    address: "0x73215fd446309f28"
    one_wire_id: one_wire_1
    name: "Temp Pod. Sypialnia"
    unit_of_measurement: "°C"
    icon: "mdi:water-percent"
    device_class: "temperature"
    state_class: "measurement"
    accuracy_decimals: 1    

  - platform: dallas_temp
    id: temp_6
    address: "0x285eb5d44646be28"
    one_wire_id: one_wire_1
    name: "Temp Pod. Łazienka"
    unit_of_measurement: "°C"
    icon: "mdi:water-percent"
    device_class: "temperature"
    state_class: "measurement"
    accuracy_decimals: 1

  - platform: dallas_temp
    id: temp_7
    address: "0x270000003a0c8828"
    one_wire_id: one_wire_1
    name: "Temp grz. Łazienka"
    unit_of_measurement: "°C"
    icon: "mdi:water-percent"
    device_class: "temperature"
    state_class: "measurement"
    accuracy_decimals: 1
    

  - platform: pzemac
    current:
      name: "Grzałka - Prąd"
      internal: true
      id: grzalka_prad
    voltage:
      name: "Grzałka - Napięcie"
      internal: true
      id: grzalka_napiecie
    energy:
      name: "Grzałka - Energia"
      id: grzalka_energia
    power:
      name: "Grzałka - Moc"
      id: grzalka_moc
    frequency:
      name: "Grzałka - Częstotliwość"
      internal: true
      id: grzalka_czestotliwosc
    power_factor:
      name: "Grzałka - Wsp. mocy"
      internal: true
      id: grzalka_wsp_mocy
    update_interval: 5s


switch:
      
  - platform: gpio
    name: "Ogrzewanie - Grzejnik"
    pin:
      number: 17
      mode:
        output: true
      inverted: true
    restore_mode: RESTORE_DEFAULT_ON

  - platform: gpio
    name: "Ogrzewanie - Łazienka"    
    pin:
      number: 2
      mode:
        output: true
      inverted: true
    restore_mode: RESTORE_DEFAULT_ON      

  - platform: gpio
    name: "Ogrzewanie Salon I"
    pin:
      number: 16
      mode:
        output: true
      inverted: true
    restore_mode: RESTORE_DEFAULT_OFF      
  
  - platform: gpio
    name: "Ogrzewanie Salon II"
    pin:
      number: 0
      mode:
        output: true
      inverted: true
    restore_mode: RESTORE_DEFAULT_OFF

  - platform: gpio
    name: "Ogrzewanie Kuchnia"
    pin:
      number: 4
      mode:
        output: true
      inverted: true
    restore_mode: RESTORE_DEFAULT_OFF      
      
  - platform: gpio
    name: "Ogrzewanie - Pokój"
    pin:
      number: 5
      mode:
        output: true
      inverted: true
    restore_mode: RESTORE_DEFAULT_OFF
      
  - platform: gpio
    name: "Ogrzewanie - Sypialnia"
    pin:
      number: 18
      mode:
        output: true
      inverted: true
    restore_mode: RESTORE_DEFAULT_OFF
    
  - platform: gpio
    name: "Grzałka przekaznik"
    id: grzalka_przekaznik
    pin:
      number: 19
      mode:
        output: true
      inverted: true
    restore_mode: RESTORE_DEFAULT_ON
      
select:
  - platform: logger
    name: "Logger select"

    