esphome:
  name: ogrzewanie-mcu
  friendly_name: Sterownik Ogrzewania
  name_add_mac_suffix: false
  project:
    name: iot.home
    version: '1.0'

packages:
  1wire: !include ogrzewanie/1wire.yaml
  pzemac: !include ogrzewanie/pzemac.yaml
  i2c: !include ogrzewanie/i2c.yaml
  wifi: !include ogrzewanie/wifi.yaml
  api: !include ogrzewanie/api.yaml
  logging: !include ogrzewanie/logging.yaml
  heating: !include ogrzewanie/heating.yaml

esp32:
  board: esp32dev
  framework:
    type: arduino
    version: recommended


web_server:
  port: 8080
  version: 3
  include_internal: true

uart:
  rx_pin: 3
  tx_pin: 1
  baud_rate: 9600

binary_sensor:
  - platform: template
    name: "Grzałka - Stan"
    lambda: |-
      return (id(grzalka_moc).state > 5.0);
    id: grzalka_status


sensor:
  - platform: uptime
    name: "Uptime"
    id: mcu_uptime
