esphome:
  name: ogrzewanie-mcu
  friendly_name: Sterownik Ogrzewania
  name_add_mac_suffix: false
  project:
    name: iot.home
    version: '1.0'

packages:
  1wire: !include ogrzewanie/1wire.yaml
  pzemac: !include ogrzewanie/pzemac.yaml

esp32:
  board: esp32dev
  framework:
    type: arduino
    version: recommended

mdns:
  disabled: false

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: ".iot.home.arpa"
  
  ap:
    ssid: "Ogrzewanie MCU AP"
    password: "kukuryku"

modbus:
  
logger:
  baud_rate: 0

api:
  password: ""  

ota:
  platform: esphome
  password: ""

web_server:
  port: 8080
  version: 3
  include_internal: true

uart:
  rx_pin: 3
  tx_pin: 1
  baud_rate: 9600

i2c:
  sda: GPIO23
  scl: GPIO22
  scan: false

binary_sensor:
  - platform: template
    name: "Grzałka - Stan"
    lambda: |-
      return (id(grzalka_moc).state > 5.0);
    id: grzalka_status


sensor:
  - platform: uptime
    name: "Uptime"
    id: mcu_uptime

  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    name: "WiFi Signal dB"
    id: wifi_signal_db
    update_interval: 30s
    entity_category: "diagnostic"

  - platform: copy # Reports the WiFi signal strength in %
    source_id: wifi_signal_db
    name: "WiFi Signal Percent"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "Signal %"
    entity_category: "diagnostic"
    device_class: ""
    
switch:      
  - platform: gpio
    name: "Ogrzewanie - Grzejnik"
    pin:
      number: 17
      mode:
        output: true
      inverted: true
    restore_mode: RESTORE_DEFAULT_ON

  - platform: gpio
    name: "Ogrzewanie - Łazienka"    
    pin:
      number: 2
      mode:
        output: true
      inverted: true
    restore_mode: RESTORE_DEFAULT_ON      

  - platform: gpio
    name: "Ogrzewanie Salon I"
    pin:
      number: 16
      mode:
        output: true
      inverted: true
    restore_mode: RESTORE_DEFAULT_OFF      
  
  - platform: gpio
    name: "Ogrzewanie Salon II"
    pin:
      number: 0
      mode:
        output: true
      inverted: true
    restore_mode: RESTORE_DEFAULT_OFF

  - platform: gpio
    name: "Ogrzewanie Kuchnia"
    pin:
      number: 4
      mode:
        output: true
      inverted: true
    restore_mode: RESTORE_DEFAULT_OFF      
      
  - platform: gpio
    name: "Ogrzewanie - Pokój"
    pin:
      number: 5
      mode:
        output: true
      inverted: true
    restore_mode: RESTORE_DEFAULT_OFF
      
  - platform: gpio
    name: "Ogrzewanie - Sypialnia"
    pin:
      number: 18
      mode:
        output: true
      inverted: true
    restore_mode: RESTORE_DEFAULT_OFF
    
  - platform: gpio
    name: "Grzałka przekaznik"
    id: grzalka_przekaznik
    pin:
      number: 19
      mode:
        output: true
      inverted: true
    restore_mode: RESTORE_DEFAULT_ON
      
select:
  - platform: logger
    name: "Logger select"
    