packages:
  project: !include common/project.yaml
  wifi: !include common/wifi.yaml
  api: !include common/api.yaml
  diag: !include common/diag.yaml
  logger: !include common/logger.yaml
  webserver: !include common/webserver.yaml
  board: !include common/board-arduino.yaml
  ota: !include common/ota.yaml

  bme280_sensor: !include piec/bme280_sensor.yaml
  ld2410_sensor: !include piec/ld2410_sensor.yaml
  light_sensor: !include piec/light_sensor.yaml
  heating: !include piec/heating.yaml

esphome:  
  name: piec
  friendly_name: Piec / Cz. ruchu
  comment: "Moduł pieca / czujnik ruchu"

wifi:
  manual_ip:
      static_ip: 10.1.30.3
  ap:
    ssid: "piec-esp-mcu"
    password: "kukuryku"

i2c:
  sda: GPIO23
  scl: GPIO22
  scan: false

uart:
  tx_pin: GPIO1
  rx_pin: GPIO3
  baud_rate: 256000
  id: uart_sensor

web_server:
  sorting_groups:
    - id: heating_group
      name: "Ogrzewanie"
      sorting_weight: 4
      
    - id: advanced_group
      name: "Zaawansowane"
      sorting_weight: 10
    - id: bme280_sensor
      name: "BME280"
      sorting_weight: 8

