packages:
  common: !include common/base.yaml
  ota: !include common/ota.yaml
      
esphome:
  name: piec
  friendly_name: Piec / Cz. ruchu
  comment: "Moduł pieca / czujnik ruchu"
  name_add_mac_suffix: false
  project:
    name: iot.home
    version: '1.0'

esp32:
  board: esp32dev
  framework:
    type: esp-idf

    version: recommended

wifi:
  manual_ip:
      static_ip: 10.1.30.3
      gateway: 10.1.30.1
      subnet: 255.255.255.0

uart:  
  tx_pin: 1
  rx_pin: 3
  baud_rate: 115200
  parity: NONE
  stop_bits: 1

web_server:
  port: 8080
  version: 3
  sorting_groups:
    - id: heating_group
      name: "Ogrzewanie"
      sorting_weight: 10
      
ld2410:

light:
  - platform: status_led
    name: "Status LED"
    pin: GPIO2

binary_sensor:
  - platform: ld2410
    has_target:
      name: Presence
    has_moving_target:
      name: Detekcja ruchu
    has_still_target:
      name: Still Target
    out_pin_presence_status:
      name: Wykryta obecność

  - platform: gpio
    pin: 22
    name: Obecność (PIN)
    device_class: presence
    
switch:
  - platform: ld2410
    engineering_mode:
      name: "engineering mode"
    bluetooth:
      name: "control bluetooth"
      
  - platform: gpio
    pin: 
      number: GPIO21                      
      inverted: true
    name: "Grzanie piec"
    web_server:
      sorting_group_id: heating_group
    
    
select:
  - platform: ld2410
    distance_resolution:
      name: "distance resolution"
    baud_rate:
      name: "baud rate"
    light_function:
      name: light function
    out_pin_level:
      name: out pin level    

button:
  - platform: ld2410
    factory_reset:
      name: "factory reset"
    restart:
      name: "restart"
    query_params:
      name: query params

number:
  - platform: ld2410

    timeout:
      name: timeout

    light_threshold:
      name: light threshold

    max_move_distance_gate:      
      name: max move distance gate

    max_still_distance_gate:
      name: max still distance gate
    g0:
      move_threshold:
        name: g0 move threshold
      still_threshold:
        name: g0 still threshold
    g1:
      move_threshold:
        name: g1 move threshold
      still_threshold:
        name: g1 still threshold
    g2:
      move_threshold:
        name: g2 move threshold
      still_threshold:
        name: g2 still threshold
    g3:
      move_threshold:
        name: g3 move threshold
      still_threshold:
        name: g3 still threshold
    g4:
      move_threshold:
        name: g4 move threshold
      still_threshold:
        name: g4 still threshold
    g5:
      move_threshold:
        name: g5 move threshold
      still_threshold:
        name: g5 still threshold
    g6:
      move_threshold:
        name: g6 move threshold
      still_threshold:
        name: g6 still threshold
    g7:
      move_threshold:
        name: g7 move threshold
      still_threshold:
        name: g7 still threshold    
