substitutions:
  reboot_timeout: 60min
  static_ip: 10.1.30.35
  device_name: lazienka-piec
  friendly_name: Sterownik pieca
  area: "Łazienka"
  comment: "Piec | Łazienka | IP ${static_ip}"
  icon: "mdi:light"
  project_name: "piec.iot"
  project_version: "2.0"
  ap_ssid: "Piec MCU"
  
packages:  
  light: !include common/c6/status-led.yaml
  wifi: !include common/wifi.yaml
  ota: !include common/ota.yaml
  api: !include common/api.yaml
  logger: !include common/logger.yaml
  webserver: !include common/webserver.yaml

  diag: !include piec-v2/diag.yaml    
  heating: !include piec-v2/heating.yaml
  lux: !include piec-v2/light_sensor.yaml
#  presence: !include piec-v2/presence_sensor.yaml
#  ld2410_sensor: !include piec/ld2410_sensor.yaml
  climate: !include piec-v2/climate_sensor.yaml  

esphome:
  min_version: 2025.5.0
  name_add_mac_suffix: false
  name: ${device_name}
  friendly_name: ${friendly_name}
  comment: ${comment}
  area: ${area}
  project:
    name: ${project_name}
    version: ${project_version}    

esp32:
  board: esp32-c6-devkitc-1
  variant: esp32c6
  framework:
    type: esp-idf

i2c:
  sda: GPIO7
  scl: GPIO6
  frequency: 400kHz
  scan: true

logger:
  logs:
    i2c: DEBUG
    bme280: DEBUG

uart:
  id: uart_sensor
  rx_pin: GPIO4  
  tx_pin: GPIO5
  baud_rate: 256000
  
web_server:
  port: 8080
  include_internal: true
  log: true
  version: 3
  sorting_groups:
    - id: advanced_group
      name: "Zaawansowane"
      sorting_weight: 10

    - id: heating_group
      name: "Ogrzewanie"
      sorting_weight: 4

    - id: presence_group
      name: "Detekcja obecności"
      sorting_weight: 5      
      
    - id: climate_group
      name: "Klimat"
      sorting_weight: 6    
    

    - id: device_info_group
      name: "Info"
      sorting_weight: 11

