packages:
  common: !include common/base.yaml
  #esp32: !include common/board-esp-idf.yaml
  ota: !include common/ota.yaml

esp32:
  board: esp32dev
  framework:
    type: arduino

esphome:  
  name_add_mac_suffix: false
  project:
    name: iot.home
    version: '1.0'
  name: piec
  friendly_name: Piec / Cz. ruchu
  comment: "Moduł pieca / czujnik ruchu"

logger:
  baud_rate: 0

api:
  password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  manual_ip:
      static_ip: 10.1.30.3
      gateway: 10.1.30.1
      subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "piec-esp-mcu"
    password: "kukuryku"

i2c:
  sda: GPIO23
  scl: GPIO22
  scan: true

uart:
  tx_pin: GPIO1
  rx_pin: GPIO3
  baud_rate: 256000
  id: uart_sensor
  #parity: NONE
  #stop_bits: 1

web_server:
  port: 8080
  version: 3
  include_internal: true

  sorting_groups:
    - id: heating_group
      name: "Ogrzewanie"
      sorting_weight: 4
      
    - id: advanced_group
      name: "Zaawansowane"
      sorting_weight: 10
    - id: bme280_sensor

      name: "BME280"
      sorting_weight: 8
      
ld2410:
  - id: "czujnik_obecnosci_lazienka"
    uart_id: uart_sensor
    
button:
  - platform: ld2410
    factory_reset:
      name: "factory reset"
    restart:
      name: "restart"
    query_params:
      name: query params

light:
  - platform: status_led
    name: "Status LED"
    pin: GPIO2
    web_server:
      sorting_group_id: advanced_group    

switch:
  - platform: gpio
    id: wlacznik_pieca
    pin:
      number: GPIO5
      inverted: true
      mode: 
        output: true
    restore_mode: RESTORE_DEFAULT_ON
    name: "Sterownik pieca"
    web_server:
      sorting_group_id: heating_group

  - platform: ld2410
    engineering_mode:
      name: "engineering mode"      
      web_server:
        sorting_group_id: advanced_group      
    bluetooth:
      name: "control bluetooth"
      web_server:
        sorting_group_id: advanced_group

select:
  - platform: logger
    name: "Logger select"
    web_server:
      sorting_group_id: advanced_group

  - platform: ld2410
    distance_resolution:
      name: "distance resolution"
      web_server:
        sorting_group_id: advanced_group      
    baud_rate:
      name: "baud rate"
      web_server:
        sorting_group_id: advanced_group      
    light_function:
      name: light function
    out_pin_level:
      name: out pin level

              
sensor:
  - platform: adc
    pin: GPIO33
    name: "Jasność pomieszczenia"
    update_interval: 10s
    attenuation: auto  
    id: piec_jasnosc

  - platform: bme280_i2c
    address: 0x76
    temperature:
      oversampling: 16x
      name: "[BME280] Temperatura"
      id: piec_temperatura
      web_server:
        sorting_group_id: bme280_sensor            
    humidity:
      oversampling: 16x      
      name: "[BME280] Wilgotność"
      id: piec_wilgotnosc
      web_server:
        sorting_group_id: bme280_sensor
    iir_filter: 16x
    update_interval: 10s
    pressure:
      oversampling: 16x
      name: "[BME280] Ciśnienie lokalne"
      id: piec_cisnienie
      internal: true
      web_server:
        sorting_group_id: bme280_sensor                  
  - platform: template  
    name: "[BME280] Cisnienie"
    id: piec_cisnienie_abs
    lambda: |-
      float altitude = id(standard_altitude).state;
      return id(piec_cisnienie).state / powf(1 - ((0.0065 * altitude) /
        (id(piec_temperatura).state + (0.0065 * altitude) + 273.15)), 5.257);
    update_interval: 10s
    unit_of_measurement: 'hPa'   
    web_server:
      sorting_group_id: bme280_sensor  

  - platform: ld2410
    light:
      name: light
    moving_distance:
      name : Moving Distance
    still_distance:
      name: Still Distance
    moving_energy:
      name: Move Energy
    still_energy:
      name: Still Energy
    detection_distance:
      name: Detection Distance
    g0:
      move_energy:
        name: g0 move energy
        internal: true        
      still_energy:
        name: g0 still energy
        internal: true

    g1:
      move_energy:
        name: g1 move energy
        internal: true        
      still_energy:
        name: g1 still energy
        internal: true        

    g2:
      move_energy:
        name: g2 move energy
        internal: true
      still_energy:
        name: g2 still energy
        internal: true

    g3:
      move_energy:
        name: g3 move energy
        internal: true
      still_energy:
        name: g3 still energy
        internal: true

    g4:
      move_energy:
        name: g4 move energy
        internal: true
      still_energy:
        name: g4 still energy
        internal: true

    g5:
      move_energy:
        name: g5 move energy
        internal: true
      still_energy:
        name: g5 still energy
        internal: true

    g6:
      move_energy:
        name: g6 move energy
        internal: true
      still_energy:
        name: g6 still energy
        internal: true

    g7:
      move_energy:
        name: g7 move energy
        internal: true
      still_energy:
        name: g7 still energy
        internal: true

    g8:
      move_energy:
        name: g8 move energy
        internal: true
      still_energy:
        name: g8 still energy
        internal: true

      
number:
  - platform: template
    name: "Wysokość n.p.m."
    id: standard_altitude
    optimistic: true
    initial_value: 263.0
    min_value: -100.0
    max_value: 1000.0
    step: 1.0
    unit_of_measurement: "m"
    mode: box
    restore_value: true
    entity_category: config
    internal: true
    web_server:
      sorting_group_id: advanced_group
  - platform: ld2410
    timeout:
      name: timeout
    light_threshold:
      name: light threshold
    max_move_distance_gate:
      name: max move distance gate
    max_still_distance_gate:
      name: max still distance gate
    g0:
      move_threshold:
        name: g0 move threshold
      still_threshold:
        name: g0 still threshold
    g1:
      move_threshold:
        name: g1 move threshold
      still_threshold:
        name: g1 still threshold
    g2:
      move_threshold:
        name: g2 move threshold
      still_threshold:
        name: g2 still threshold
    g3:
      move_threshold:
        name: g3 move threshold
      still_threshold:
        name: g3 still threshold
    g4:
      move_threshold:
        name: g4 move threshold
      still_threshold:
        name: g4 still threshold
    g5:
      move_threshold:
        name: g5 move threshold
      still_threshold:
        name: g5 still threshold
    g6:
      move_threshold:
        name: g6 move threshold
      still_threshold:
        name: g6 still threshold
    g7:
      move_threshold:
        name: g7 move threshold
      still_threshold:
        name: g7 still threshold
    g8:
      move_threshold:
        name: g8 move threshold
      still_threshold:
        name: g8 still threshold
      

binary_sensor:
  - platform: ld2410
    has_target:
      name: Presence
    has_moving_target:
      name: Moving Target
    has_still_target:
      name: Still Target
    out_pin_presence_status:
      name: out pin presence status

text_sensor:
  - platform: ld2410
    version:
      name: "firmware version"
    mac_address:
      name: "mac address"
