packages:
  common: !include common/base.yaml
  #esp32: !include common/board-esp-idf.yaml
  ota: !include common/ota.yaml

esp32:
  board: esp32dev
  framework:
    type: arduino

esphome:  
  name_add_mac_suffix: false
  project:
    name: iot.home
    version: '1.0'
  name: piec
  friendly_name: Piec / Cz. ruchu
  comment: "Moduł pieca / czujnik ruchu"

logger:
  

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  manual_ip:
      static_ip: 10.1.30.3
      gateway: 10.1.30.1
      subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "piec-esp-mcu"
    password: "kukuryku"

uart:  
  id: uart_ld2410
  tx_pin: 17
  rx_pin: 16
  baud_rate: 256000
  parity: NONE
  stop_bits: 1

web_server:
  port: 8080
  version: 3
  sorting_groups:
    - id: heating_group
      name: "Ogrzewanie"
      sorting_weight: 4
      
    - id: advanced_group
      name: "Zaawansowane"
      sorting_weight: 10
      
light:
  - platform: status_led
    name: "Status LED"
    pin: GPIO2

ld2410:
  - uart_id: uart_ld2410

    
switch:
  - platform: ld2410
    engineering_mode:
      name: "engineering mode"
    bluetooth:
      name: "control bluetooth"
  - platform: gpio
    id: wlacznik_pieca
    pin: 
      number: GPIO5
      inverted: true
    name: "Sterownik pieca"
            
select:
  - platform: logger
    name: "Logger select"  
  - platform: ld2410
    distance_resolution:
      name: "distance resolution"
    baud_rate: 
      name: "baud rate"
    light_function:
      name: light function
    out_pin_level:
      name: out pin level    

button:
  - platform: ld2410
    factory_reset:
      name: "factory reset"
    restart:
      name: "restart"
    query_params:
      name: query params

number:
  - platform: ld2410
    timeout:
      name: timeout
    light_threshold:
      name: light threshold
    max_move_distance_gate:
      name: max move distance gate
    max_still_distance_gate:
      name: max still distance gate

binary_sensor:     
  - platform: ld2410
    has_target:
      name: "Presence"
    has_moving_target:
      name: "Moving Target"
    has_still_target:
      name: "Still Target"
    out_pin_presence_status:
      name: out pin presence status
  - platform: gpio
    pin: GPIO18
    name: gpio out pin presence
    device_class: presence

sensor:
  - platform: adc
    pin: GPIO33
    name: "Jasność pomieszczenia"
    update_interval: 5s
    attenuation: auto
    #filters:
    #  - lambda: |-
    #      return (x / 10000.0) * 2000000.0;
  - platform: ld2410
    light:
      name: "light"
    moving_distance:
      name: "Moving distance (cm)"
    still_distance:
      name: "Still Distance (cm)"
    moving_energy:
      name: "Move Energy (%)"
    still_energy:
      name: "Still Energy (%)"
    detection_distance:
      name: "Distance Detection (cm)"
