esphome:
  name: esp-c6
  friendly_name: esp_c6
  name_add_mac_suffix: false
  project:
    name: iot.home
    version: '1.0'
    
esp32:
  board: esp32-c6-devkitc-1
  variant: esp32c6
  framework:
    type: esp-idf    
    platform_version: 6.9.0
    version: 5.3.1
    
mdns:
  disabled: false

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  - platform: esphome
    password: ''


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: ".iot.home.arpa"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp-C6 Fallback Hotspot"
    password: "kukuryku"

esp32_improv:
  authorizer: none

#Allow provisioning Wi-Fi via serial
improv_serial:

captive_portal:

dashboard_import:
  package_import_url: github://esphome/example-configs/esphome-web/esp32.yaml@main
  import_full_config: true


# Sets up Bluetooth LE (Only on ESP32) to allow the user
# to provision wifi credentials to the device.
web_server:
  port: 8080


sensor:
  - platform: uptime
    name: "Uptime"
    id: mcu_uptime

  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    name: "WiFi Signal dB"
    id: wifi_signal_db
    update_interval: 30s
    entity_category: "diagnostic"

  - platform: copy # Reports the WiFi signal strength in %
    source_id: wifi_signal_db
    name: "WiFi Signal Percent"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "Signal %"
    entity_category: "diagnostic"
    device_class: ""  


text_sensor:
  - platform: wifi_info
    ip_address:
      name: ESP IP Address
      address_0:
        name: IP Address

    ssid:
      name: SSID
    bssid:
      name: BSSID
    mac_address:
      name: Mac Address
    scan_results:
      name: Wifi Scan Results
    dns_address:
      name: DNS Address
