packages:
  api: !include common/api.yaml
  logger: !include common/logger.yaml
  light: !include common/c6/status-led.yaml

substitutions:
  step: "5"
  interval_ms: "100"

globals:

  - id: brightness
    type: int
    restore_value: no
    initial_value: '100'
    
esphome:  
  name: kuchnia-sufit
  friendly_name: Sufit kuchnia
  min_version: 2025.5.0
  comment: "Oświetlenie, wentylacja, sensory w kuchni"
  name_add_mac_suffix: false
  project:
    name: kuchnia-sufit.iot
    version: '1.0'

esp32:
  board: esp32-c6-devkitm-1
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:
- platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: !secret network_domain
  reboot_timeout: 60min
  fast_connect: true  
  ap:
    ssid: "Kuchnia sufit MCU"    
    password: !secret ap_password
  manual_ip:
    gateway: 10.1.30.1
    subnet: 255.255.255.0
    static_ip: 10.1.30.26
    
captive_portal:

mdns:
  disabled: false  

#i2c:
#  sda: GPIO23
#  scl: GPIO22
#  scan: false

debug:
  update_interval: 5s

web_server:
  port: 8080
  include_internal: true
  log: true
  version: 3  
  sorting_groups:
    - id: advanced_group
      name: "Zaawansowane"
      sorting_weight: 10

    - id: device_info_group
      name: "Info"
      sorting_weight: 11

button:
  - platform: restart
    name: "Restart ESP"
    id: restart_esp
    web_server:
      sorting_group_id: advanced_group

  - platform: template
    id: btn_minus
    name: "Minus"
    on_press:
      then:
        - light.dim_relative:
            id: light_0
            relative_brightness: -2%
        - lambda: |-
            id(brightness) = id(light_0).current_values.get_brightness();

  - platform: template
    name: "Plus"    
    id: button_up
    on_press:
      then:
        - light.dim_relative:
            id: light_0
            relative_brightness: 2%
        - lambda: |-
            id(brightness) = id(light_0).current_values.get_brightness();

text_sensor:
  - platform: debug
    device:
      name: "Device Info"
      web_server:
        sorting_group_id: device_info_group
    reset_reason:
      name: "Reset Reason"
      web_server:
        sorting_group_id: device_info_group

  - platform: uptime
    name: Uptime

  - platform: version
    name: "ESPHome version"

  - platform: template
    name: "Project Version"
    id: esphome_project_version_text_short
    icon: "mdi:information-box"
    entity_category: "diagnostic"
    update_interval: 600s
    lambda: |-
      return { ESPHOME_PROJECT_VERSION };

  - platform: template
    name: "Project Version Detailed"
    id: esphome_project_version_text_detailed
    icon: "mdi:information-box"
    entity_category: "diagnostic"
    update_interval: 600s
    lambda: |-
      return { ESPHOME_PROJECT_VERSION " " + App.get_compilation_time() };

  - platform: template
    name: "Project Name"
    id: esphome_project_name
    icon: "mdi:information-box"
    entity_category: "diagnostic"
    update_interval: 600s
    lambda: |-
      return { ESPHOME_PROJECT_NAME };

binary_sensor:
  - platform: status
    name: "Status"     
    web_server:
      sorting_group_id: device_info_group

  - platform: gpio  
    name: "SW-1"
    id: "input_sw_1"
    
    pin:
      number: GPIO0
      inverted: true
      mode:
        input: true
        pullup: true

    on_click:
      - min_length: 50ms
        max_length: 750ms
        then: 
        - if:
            condition:
              light.is_off: light_0
            then:
              - light.turn_on:
                  id: light_0
                  brightness: 50%
            else:            
              - light.dim_relative:
                  id: light_0
                  relative_brightness: 2%
                  transition_length: 0.02s
                  brightness_limits:
                      min_brightness: 0%
                      max_brightness: 100%
              - delay: 0.05s
    on_press:      
      - while:
          condition:
            binary_sensor.is_on: input_sw_1
          then:
            - light.dim_relative:
                id: light_0
                relative_brightness: 1%
                transition_length: 0.02s
                brightness_limits:
                    min_brightness: 0%
                    max_brightness: 100%
            - delay: 0.05s

  - platform: gpio
    name: "SW-2"
    id: "input_sw_2"
      
    pin:
      number: GPIO1
      inverted: true
      mode:      
        input: true
        pullup: true
    on_click:
      - min_length: 50ms
        max_length: 750ms
        then:
          - if:
              condition:
                light.is_on: light_0
              then:
                - light.turn_off: light_0
    on_press:      
      - while:
          condition:
            binary_sensor.is_on: input_sw_2
          then:
            - light.dim_relative:
                id: light_0
                relative_brightness: -1%
                transition_length: 0.02s
                brightness_limits:
                    min_brightness: 0%
                    max_brightness: 100%
            - delay: 0.05s

output:
  - platform: ledc
    pin: GPIO4
    id: output_led
    frequency: 200Hz
    zero_means_zero: true
number:
  - platform: template
    name: pwm_change
    optimistic: true
    initial_value: 200
    min_value: 50
    max_value: 2000
    step: 100
    mode: box
    on_value:
      - output.ledc.set_frequency:
          id: output_led
          frequency: !lambda |-
            return x;

light:
  - platform: monochromatic
    id: light_0
    name: "Kuchnia LED"
    output: output_led
    restore_mode: RESTORE_DEFAULT_OFF
    effects:
      - pulse:
          name: "Szybki impuls"
          transition_length: 0.4s
          update_interval: 1.5s
          min_brightness: "30%"
          max_brightness: "100%"
      - random:
          name: "Losowy efekt"
          transition_length: 3s
          update_interval: 5s
      - pulse:
          name: "Wolny impuls"
          transition_length: 500ms
          update_interval: 2s
      - pulse:
          name: "Asymetryczny impuls"
          transition_length:
            on_length: 1s
            off_length: 500ms
          update_interval: 1.5s
