substitutions:
  static_ip_address: 10.1.30.26
  device_name: kuchnia-sufit
  friendly_name: Sufit kuchnia
  comment: "Oświetlenie, wentylacja, sensory w kuchni | IP ${static_ip_address}"
  icon: "mdi:light"
  
  project_name: "kuchnia-sufit.iot"
  project_version: "1.0"

  light_switch_gpio: GPIO20
  light_output_pwm_gpio: GPIO21
  fan_relay_gpio: GPIO22
  fan_hi_speed_gpio: GPIO23
  fan_switch_gpio: GPIO15

  esphome_min_version: 2025.5.0  
  static_ip_gateway: 10.1.30.1
  static_ip_netmask: 255.255.255.0  
  ap_ssid: ${friendly_name} AP"
  web_server_port: "8080"
  reboot_timeout: 60min  
  
packages:
  api: !include common/api.yaml  
  logger: !include common/logger.yaml
  statusLight: !include common/c6/status-led.yaml
  ota: !include common/ota.yaml
  diag: !include common/diagnostic.yaml
  fan: !include sufit-kuchnia/fan.yaml
  light: !include sufit-kuchnia/light.yaml
  wifi: !include sufit-kuchnia/wifi.yaml
  server: !include sufit-kuchnia/webserver.yaml

esp32:
  board: esp32-c6-devkitm-1
  framework:
    type: esp-idf

esphome:
  min_version: ${esphome_min_version}
  name: ${device_name}
  friendly_name: ${friendly_name}
  comment: ${comment}
  name_add_mac_suffix: false
  project:
    name: ${project_name}
    version: ${project_version}

  devices:
    - id: kitchen_light
      name: "Oświetlenie kuchni"
      area_id: kitchen_area

    - id: kitchen_fan
      name: "Wentylator"
      area_id: kitchen_area
  
  areas:
    - id: kitchen_area
      name: "Kuchnia"
