substitutions:
  reboot_timeout: 60min
  static_ip: 10.1.30.24
  device_name: lazienka-oswietlenie
  friendly_name: Oświetlenie Łazienki
  area: ""
  comment: "Oświetlenie LED / Lampa w łazience | IP ${static_ip}"
  icon: "mdi:light"
  project_name: "oswietlenie-lazienka.iot"
  project_version: "1.0"  
  ap_ssid: "Oswietlenie MCU"

packages:
  logger: !include common/logger.yaml
  light: !include common/c6/status-led.yaml
  wifi: !include common/wifi.yaml
  ota: !include common/ota.yaml

api:
  password: !secret homeassistant_api_key

esphome:
  min_version: 2025.5.0
  name_add_mac_suffix: false
  name: ${device_name}
  friendly_name: ${friendly_name}
  comment: ${comment}
  area: ${area}
  project:
    name: ${project_name}
    version: ${project_version}    

esp32:
  board: esp32-c6-devkitm-1
  framework:
    type: esp-idf

#i2c:
#  sda: GPIO23
#  scl: GPIO22
#  scan: false

web_server:
  port: 8080
  include_internal: true
  log: true
  version: 3
  sorting_groups:
    - id: advanced_group
      name: "Zaawansowane"
      sorting_weight: 10

    - id: device_info_group
      name: "Info"
      sorting_weight: 11

button:
  - platform: restart
    name: "Restart ESP"
    id: restart_esp
    web_server:
      sorting_group_id: advanced_group
      
text_sensor:
  - platform: debug
    device:
      name: "Device Info"
      web_server:
        sorting_group_id: device_info_group
    reset_reason:
      name: "Reset Reason"
      web_server:
        sorting_group_id: device_info_group

  - platform: uptime
    name: Uptime

  - platform: version
    name: "ESPHome version"

  - platform: template
    name: "Project Version"
    id: esphome_project_version_text_short
    icon: "mdi:information-box"
    entity_category: "diagnostic"
    update_interval: 600s
    lambda: |-
      return { ESPHOME_PROJECT_VERSION };

  - platform: template
    name: "Project Version Detailed"
    id: esphome_project_version_text_detailed
    icon: "mdi:information-box"
    entity_category: "diagnostic"
    update_interval: 600s
    lambda: |-
      return { ESPHOME_PROJECT_VERSION " " + App.get_compilation_time() };

  - platform: template
    name: "Project Name"
    id: esphome_project_name
    icon: "mdi:information-box"
    entity_category: "diagnostic"
    update_interval: 600s
    lambda: |-
      return { ESPHOME_PROJECT_NAME };

binary_sensor:
  - platform: status
    name: "Status"     
    web_server:
      sorting_group_id: device_info_group
  - platform: gpio
    pin:
      number: GPIO21
      mode:
        input: true
        pullup: true
    name: "SW-1"
    id: "input_sw_1"
    filters:
      - delayed_on: 10ms
      - delayed_off: 10ms

  - platform: gpio
    pin:
      number: GPIO22
      mode:
        input: true
        pullup: true
    name: "SW-2"
    id: "input_sw_2"
    filters:
      - delayed_on: 10ms
      - delayed_off: 10ms

  - platform: gpio
    pin:
      number: GPIO23
      mode:
        input: true
        pullup: true
    name: "SW-3"
    id: "input_sw_3"
    filters:
      - delayed_on: 10ms
      - delayed_off: 10ms