sensor:
  - platform: bh1750
    name: "Natężenie światła"
    address: 0x23
    id: bh1750_lux
    update_interval: 30s

binary_sensor:
  - platform: template
    name: "Tryb nocny"
    id: tryb_nocny
    device_class: light
    lambda: |-
      float lux = id(bh1750_lux).state;
      float threshold = id(prog_jasnosci_noc).state;

      if (lux < threshold) {
        return true;
      } else {
        return false;
      }        

number:
  - platform: template
    name: "Próg jasności (noc)"
    id: prog_jasnosci_noc
    optimistic: true
    min_value: 0
    max_value: 100
    step: 0.1
    restore_value: true
    initial_value: 5
    mode: box

