esphome:
  name_add_mac_suffix: false
  project:
    name: iot.home
    version: '1.0'

mdns:
  disabled: false

esp32:
  board: esp32dev
  framework:
    type: arduino
    version: recommended
    

improv_serial:
captive_portal:

esp32_improv:
  authorizer: none

    
#    type: esp-idf
#    version: recommended
    # Custom sdkconfig options
#    sdkconfig_options:
#      COMPILER_OPTIMIZATION_SIZE: y
    # Advanced tweaking options
#    advanced:
#      ignore_efuse_mac_crc: false

# Wspólne komponenty
<<: !include wifi.yaml
<<: !include ota.yaml
<<: !include api.yaml
<<: !include logger.yaml
<<: !include webserver.yaml


