esphome:
  name_add_mac_suffix: false
  project:
    name: iot.home
    version: '1.0'
esp32:
  board: esp32dev
  framework:
    type: arduino
    version: recommended
    
# Wspólne komponenty
<<: !include wifi.yaml
<<: !include api.yaml
<<: !include logger.yaml
<<: !include webserver.yaml
