
esp32:
  board: esp32dev
  framework:
    type: esp-idf
    version: recommended
    # Custom sdkconfig options
    sdkconfig_options:
      COMPILER_OPTIMIZATION_SIZE: y
    # Advanced tweaking options
    advanced:
      ignore_efuse_mac_crc: false

mdns:
  disabled: true
  
# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:
- platform: esphome

status_led:
  pin: GPIO04

# Allow provisioning Wi-Fi via serial
improv_serial:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: .${domain}
  use_address: ${name}.${domain}
  reboot_timeout: 60min
  fast_connect: true
  ap: {}
  
dashboard_import:
  package_import_url: github://esphome/example-configs/esphome-web/esp32.yaml@main
  import_full_config: true

# Sets up Bluetooth LE (Only on ESP32) to allow the user
# to provision wifi credentials to the device.
esp32_improv:
  authorizer: none

web_server:
  port: 80
  enable_private_network_access: true
  include_internal: false
  ota: true
  log: true
  local: true
  
  css_include: './v2/webserver-v1.min.css'
  js_include: "./v2/www.js"
  
  css_url: "https://esphome.io/_static/webserver-v1.min.css"
  js_url: "https://esphome.io/_static/www.js"
  version: 2

captive_portal: {}

