text_sensor:
  - platform: debug
    device:
      name: "Urządzenie"
      web_server:
        sorting_group_id: device_info_group
      internal: true
    reset_reason:
      name: "Powód resetu"
      web_server:
        sorting_group_id: device_info_group

  - platform: uptime
    name: Uptime

  - platform: version
    name: "ESPHome"
    internal: true

  - platform: template
    name: "Wersja"
    internal: true    
    id: esphome_project_version_text_short
    icon: "mdi:information-box"
    entity_category: "diagnostic"
    update_interval: 600s
    lambda: |-
      return { ESPHOME_PROJECT_VERSION };

  - platform: template
    name: "Szczegóły"
    id: esphome_project_version_text_detailed
    icon: "mdi:information-box"
    entity_category: "diagnostic"
    update_interval: 600s
    lambda: |-
      return { ESPHOME_PROJECT_VERSION " " + App.get_compilation_time() };

  - platform: template
    name: "Projekt"
    id: esphome_project_name
    icon: "mdi:information-box"
    entity_category: "diagnostic"
    update_interval: 600s
    lambda: |-
      return { ESPHOME_PROJECT_NAME };

# Status urządzenia
binary_sensor:
  - platform: status
    name: "Status"
    web_server:
      sorting_group_id: device_info_group


# Restart ESP
button:
  - platform: restart
    name: "Restart ESP"
    id: restart_esp
    web_server:
      sorting_group_id: advanced_group