switch:
  - platform: gpio
    id: fan_relay
    name: "Wentylator"
    device_id: kitchen_fan
    pin: ${fan_relay_gpio}
    restore_mode: RESTORE_DEFAULT_OFF
    inverted: true
    web_server:
      sorting_group_id: fan_group

  - platform: gpio
    id: fan_high_speed
    name: "II bieg"
    device_id: kitchen_fan
    pin: ${fan_hi_speed_gpio}
    restore_mode: RESTORE_DEFAULT_OFF
    inverted: true
    web_server:
      sorting_group_id: fan_group

binary_sensor:
  - platform: gpio    
    pin:
      number: ${fan_switch_gpio}
      mode:
        input: true
        pullup: true
      inverted: true
    name: "Włącznik"
    id: fan_button
    web_server:
      sorting_group_id: fan_group
    filters:
      - delayed_on_off: ${debounce_time}
    on_click:
      - switch.toggle: fan_relay


esphome:
  on_boot:
    priority: -100
    then:
      - switch.turn_off: fan_relay
      - switch.turn_off: fan_high_speed