wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: !secret network_domain
  reboot_timeout: 60min
  fast_connect: true 
  ap:
    ssid: ${ap_ssid}
    password: !secret ap_password
  manual_ip:
    gateway: ${static_ip_gateway}
    subnet: ${static_ip_netmask}
    static_ip: ${static_ip_address}

captive_portal: {}

mdns: 
  disabled: true

sensor:
  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    name: "WiFi Signal dB"
    id: wifi_signal_db
    update_interval: 30s
    entity_category: "diagnostic"
    web_server:
      sorting_group_id: device_info_group

  - platform: copy # Reports the WiFi signal strength in %
    source_id: wifi_signal_db
    name: "WiFi Signal Percent"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "Signal %"
    entity_category: "diagnostic"
    device_class: ""
    web_server:
      sorting_group_id: device_info_group
    
