
one_wire:
  - platform: gpio
    pin: GPIO14
    id: one_wire_1

  - platform: gpio
    pin: GPIO27
    id: one_wire_2


button:
  - platform: template
    name: "Test 1-wire bus"
    internal: true
    on_press: 
      then:
        - lambda: |-
            id(one_wire_1).search();
            id(one_wire_1).dump_config();

sensor:
  - platform: dallas_temp
    id: temp_1
    address: "0xcc65c7d446950328"
    one_wire_id: one_wire_1
    name: "Temp Pod. Salon #1"
    unit_of_measurement: "°C"
    icon: "mdi:water-percent"
    device_class: "temperature"
    state_class: "measurement"
    accuracy_decimals: 1    

  - platform: dallas_temp  
    id: temp_2
    one_wire_id: one_wire_1
    address: "0x9751cfd446dd8928"
    name: "Temp Pod. Salon #2"
    unit_of_measurement: "°C"
    icon: "mdi:water-percent"
    device_class: "temperature"
    state_class: "measurement"
    accuracy_decimals: 1    
    
  - platform: dallas_temp
    id: temp_3  
    address: "0x943c01e076247d28"
    name: "Temp Pod. Salon #3"
    one_wire_id: one_wire_1
    unit_of_measurement: "°C"
    icon: "mdi:water-percent"
    device_class: "temperature"
    state_class: "measurement"
    accuracy_decimals: 1
    
  - platform: dallas_temp
    id: temp_4
    address: "0x9e3c01e076378028"
    one_wire_id: one_wire_1
    name: "Temp Pod. Pokój"
    unit_of_measurement: "°C"
    icon: "mdi:water-percent"
    device_class: "temperature"
    state_class: "measurement"
    accuracy_decimals: 1    

  - platform: dallas_temp
    id: temp_5
    address: "0x73215fd446309f28"
    one_wire_id: one_wire_1
    name: "Temp Pod. Sypialnia"
    unit_of_measurement: "°C"
    icon: "mdi:water-percent"
    device_class: "temperature"
    state_class: "measurement"
    accuracy_decimals: 1

  - platform: dallas_temp
    id: temp_6
    address: "0x285eb5d44646be28"
    one_wire_id: one_wire_1
    name: "Temp Pod. Łazienka"
    unit_of_measurement: "°C"
    icon: "mdi:water-percent"
    device_class: "temperature"
    state_class: "measurement"
    accuracy_decimals: 1

  - platform: dallas_temp
    id: temp_7
    address: "0x270000003a0c8828"
    one_wire_id: one_wire_2
    name: "Temp grz. Łazienka"
    unit_of_measurement: "°C"
    icon: "mdi:water-percent"
    device_class: "temperature"
    state_class: "measurement"
    accuracy_decimals: 1