substitutions:
    max_floor_temp: 32.0
    min_floor_temp: 26.0
    min_air_temperature: 18
    max_air_temperature: 25
    target_temperature_step: 0.5
    current_temperature_step: 0.1
    min_heating_run_time: 150sec
    min_heating_off_time: 150sec
    min_idle_time: 30sec

sensor:
  - name: "Temp. Salon"
    platform: homeassistant
    id: temperatura_salon
    entity_id: sensor.cz_t_temperature
    unit_of_measurement: "°C"    

  - name: "Temp. Łazienka"
    platform: homeassistant
    id: lazienka_temperature
    entity_id: sensor.lazienka_piec_temperatura_pomieszczenia
    unit_of_measurement: "°C"
    filters:
      - lambda: |-
          if (isnan(x)) return id(temperatura_salon).state;
          return x;

  - name: "Temp. Sypialnia"
    platform: homeassistant
    id: ht_1_temperature
    entity_id: sensor.ht_1_temperatura
    unit_of_measurement: "°C"    

  - name: "Temp. Pokój"
    platform: homeassistant
    id: ht_2_temperature
    entity_id: sensor.ht_2_temperatura
    unit_of_measurement: "°C"    

  - name: "Wilg. Salon"
    platform: homeassistant
    id: wilgotnosc_salon
    entity_id: sensor.cz_t_humidity    

  - name: "Wilg. Łazienka"
    platform: homeassistant
    id: lazienka_humidity
    entity_id: sensor.lazienka_piec_wilgotnosc_pomieszczenia    
    filters:
      - lambda: |-
          if (isnan(x)) return id(wilgotnosc_salon).state;
          return x;    

  - name: "Wilg. Sypialnia"
    platform: homeassistant
    id: ht_1_humidity
    entity_id: sensor.ht_1_wilgotnosc
    
  - name: "Wilg. Pokój"
    platform: homeassistant
    id: ht_2_humidity
    entity_id: sensor.ht_2_wilgotnosc    

binary_sensor:
  - name: "Podłoga salon #1 przegrzana"
    platform: template  
    internal: true
    lambda: |-
      return id(temp_1).state > ${max_floor_temp};
    on_press:
      - switch.turn_off: heating_salon_1

  - name: "Podłoga salon #2 przegrzana"
    platform: template
    internal: true
    lambda: |-
      return id(temp_2).state > ${max_floor_temp};
    on_press:
      - switch.turn_off: heating_salon_2

  - name: "Podłoga kuchnia przegrzana"
    platform: template
    internal: true
    lambda: |-
      return id(temp_3).state > ${max_floor_temp};
    on_press:
      - switch.turn_off: heating_kuchnia

  - name: "Podłoga pokój przegrzana"
    platform: template  
    internal: true
    lambda: |-
      return id(temp_4).state > ${max_floor_temp};
    on_press:
      - switch.turn_off: heating_pokoj

  - name: "Podłoga sypialnia przegrzana"
    platform: template
    internal: true
    lambda: |-
      return id(temp_5).state > ${max_floor_temp};
    on_press:
      - switch.turn_off: heating_sypialnia

  - name: "Podłoga łazienka przegrzana"
    platform: template
    internal: true
    lambda: |-
      return id(temp_6).state > ${max_floor_temp};
    on_press:
      - switch.turn_off: heating_lazienka

  - name: "Grzałka - Stan"
    platform: template    
    id: grzalka_status
    lambda: |-
      return (id(grzalka_prad).state > 0);
    device_id: grzalka_device
    web_server:
      sorting_group_id: grzalka_group

  - name: "Blokada pętli grzejnika"
    platform: template  
    id: blokada_obiegu_grzejnika    
    lambda: |-
      return (id(temp_7).state > ${max_floor_temp} || id(grzalka_status).state);
    web_server:
      sorting_group_id: lock_group

  - name: "Blokada grzałki"
    platform: template  
    id: blokada_grzalki
    lambda: |-
      return !id(grzalka_przekaznik).state || id(grzejnik_podlogowka).state;
    web_server:
      sorting_group_id: lock_group
    device_id: grzalka_device

climate:
  - name: "Podłogówka Salon"
    platform: thermostat      
    id: "podlogowka_salon"
    
    sensor: temperatura_salon
    humidity_sensor: wilgotnosc_salon
    
    min_idle_time: ${min_idle_time}
    min_heating_run_time: ${min_heating_run_time}
    min_heating_off_time: ${min_heating_off_time}

    heat_action:
      - switch.turn_on: heating_salon_1
      - switch.turn_on: heating_salon_2
      - switch.turn_on: heating_kuchnia
    idle_action:
      - switch.turn_off: heating_salon_1
      - switch.turn_off: heating_salon_2
      - switch.turn_off: heating_kuchnia
    
    default_preset: Home
    preset:
      - name: Home
        default_target_temperature_low: 22°C
    
    visual:
      min_temperature: ${min_air_temperature}
      max_temperature: ${max_air_temperature}
      temperature_step:
        target_temperature: ${target_temperature_step}
        current_temperature: ${current_temperature_step}

  - name: "Podłogówka Sypialnia"
    platform: thermostat    
    id: "podlogowka_sypialnia"
    sensor: ht_1_temperature
    humidity_sensor: ht_1_humidity

    min_idle_time: ${min_idle_time}
    min_heating_run_time: ${min_heating_run_time}
    min_heating_off_time: ${min_heating_off_time}

    heat_action:
      - switch.turn_on: heating_sypialnia

    idle_action:
      - switch.turn_off: heating_sypialnia

    default_preset: Home
    preset:
      - name: Home
        default_target_temperature_low: 21°C

    visual:
      min_temperature: ${min_air_temperature}
      max_temperature: ${max_air_temperature}
      temperature_step:
        target_temperature: ${target_temperature_step}
        current_temperature: ${current_temperature_step}

  - name: "Podłogówka Pokój"
    platform: thermostat
    id: "podlogowka_pokoj"    
    sensor: ht_2_temperature
    humidity_sensor: ht_2_humidity

    min_idle_time: ${min_idle_time}
    min_heating_run_time: ${min_heating_run_time}
    min_heating_off_time: ${min_heating_off_time}

    heat_action:
      - switch.turn_on: heating_pokoj
    idle_action:
      - switch.turn_off: heating_pokoj
    
    default_preset: Home
    preset:
      - name: Home
        default_target_temperature_low: 21°C

    visual:
      min_temperature: ${min_air_temperature}
      max_temperature: ${max_air_temperature}
      temperature_step:
        target_temperature: ${target_temperature_step}
        current_temperature: ${current_temperature_step}

  - name: "Podłogówka Łazienka"
    platform: thermostat    
    id: "podlogowka_lazienka"    
    sensor: lazienka_temperature
    
    min_idle_time: ${min_idle_time}
    min_heating_run_time: ${min_heating_run_time}
    min_heating_off_time: ${min_heating_off_time}
    
    heat_action:
      - switch.turn_on: heating_lazienka
    idle_action:
      - switch.turn_off: heating_lazienka
    
    default_preset: Home
    preset:
      - name: Home
        default_target_temperature_low: 22°C

    visual:
      min_temperature: ${min_air_temperature}
      max_temperature: ${max_air_temperature}
      temperature_step:
        target_temperature: ${target_temperature_step}
        current_temperature: ${current_temperature_step}
