
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: ".iot.home.arpa"
  
  ap:
    ssid: "Ogrzewanie MCU AP"
    password: "kukuryku"
    
mdns:
  disabled: false
  
sensor:
  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    name: "WiFi Signal dB"
    id: wifi_signal_db
    update_interval: 30s
    entity_category: "diagnostic"

  - platform: copy # Reports the WiFi signal strength in %
    source_id: wifi_signal_db
    name: "WiFi Signal Percent"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "Signal %"
    entity_category: "diagnostic"
    device_class: ""