substitutions: !include ../common/subs.yaml

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password  
  domain: ${domain}
  reboot_timeout: ${reboot_timeout}
  fast_connect: ${wifi_fast_connect}
  ap:
    ssid: ${friendly_name} AP"
    password: !secret ap_password
  manual_ip:
    gateway: ${static_ip_gateway}
    subnet: ${static_ip_netmask}
    static_ip: ${static_ip_address}

captive_portal: {}

mdns: 
  disabled: ${disable_mdns}

sensor:
  - platform: wifi_signal
    name: "WiFi Signal dB"
    id: wifi_signal_db
    update_interval: 30s
    entity_category: "diagnostic"
    web_server: 
      sorting_group_id: diagnostic_group
       
  - platform: copy
    source_id: wifi_signal_db
    name: "WiFi Signal Percent"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "Signal %"
    entity_category: "diagnostic"
    device_class: ""
    web_server: 
      sorting_group_id: diagnostic_group

